---
  - name: "{{ letsencrypt_cert.domains[0] }}: Attempt to get the certificate using the webroot authenticator"
    command: "{{ letsencrypt_command }} -a webroot --webroot-path {{ letsencrypt_webroot_path }} certonly"
    become: yes
    args:
      creates: "/etc/letsencrypt/live/{{ letsencrypt_cert.domains[0] }}"
