---
  - name: Ensure jessie backports are enabled
    apt_repository: repo="deb http://ftp.debian.org/debian jessie-backports main" filename="backports" state=present
    become: yes
    tags: install

  - name: Ensure certbot is installed
    apt: update_cache=yes name=certbot state=present
    become: yes
    tags: install

  - name: Get certificates for all domain groups
    include: get_cert.yml
    with_items: "{{ letsencrypt_certs }}"
    loop_control:
      loop_var: letsencrypt_cert
