---
  - apt: update_cache=yes cache_valid_time=3600
    become: yes
    tags: install

  - name: Install depends
    package: name={{ item }} state=present
    become: yes
    with_items:
      - python
      - python-dev
      - python-virtualenv
      - gcc
      - dialog
      - libaugeas0
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - python-pip
      - git
    tags: install

  - include_vars: "{{ item }}"
    with_first_found:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
    when: virtualenv_package_name is not defined
    tags: install

  - name: Install virtualenv
    package: name={{ item }} state=present
    become: yes
    with_items:
      - "{{ virtualenv_package_name }}"
    tags: install

  - name: Install python depends
    pip: virtualenv="{{ letsencrypt_venv }}" virtualenv_site_packages=no name={{ item }} state=present virtualenv_python=python2
    become: yes
    with_items:
      - setuptools
      - pip
    tags: install

  - name: More python depends
    pip: virtualenv="{{ letsencrypt_venv }}" virtualenv_site_packages=no name=letsencrypt state=present
    become: yes
    tags: install

  - name: Get certificates for all domain groups
    include: get_cert.yml
    with_items: "{{ letsencrypt_certs }}"
    loop_control:
      loop_var: letsencrypt_cert

  - name: Install renewal cron
    become: yes
    cron: name="Let's Encrypt Renewal" day="{{ letsencrypt_renewal_frequency.day }}" hour="{{ letsencrypt_renewal_frequency.hour }}" minute="{{ letsencrypt_renewal_frequency.minute }}" job="{{ letsencrypt_venv }}/bin/letsencrypt renew {{ letsencrypt_renewal_command_args }} > /dev/null"
